"""dashboard security and app ops

Revision ID: 1d70f58dd134
Revises: 9f8eb30a83d5
Create Date: 2026-05-20 17:27:14.303905

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1d70f58dd134'
down_revision = '9f8eb30a83d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_login_history_email'), 'admin_login_history', ['email'], unique=False)
    op.create_index(op.f('ix_admin_login_history_id'), 'admin_login_history', ['id'], unique=False)
    op.create_table('ip_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_blacklist_id'), 'ip_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_ip_blacklist_ip_address'), 'ip_blacklist', ['ip_address'], unique=True)
    op.add_column(
        'connected_apps',
        sa.Column('api_key_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        'connected_apps',
        sa.Column('secret_key_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('connected_apps', 'api_key_active', server_default=None)
    op.alter_column('connected_apps', 'secret_key_active', server_default=None)
    op.add_column('transactions', sa.Column('payer_phone', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payer_phone')
    op.drop_column('connected_apps', 'secret_key_active')
    op.drop_column('connected_apps', 'api_key_active')
    op.drop_index(op.f('ix_ip_blacklist_ip_address'), table_name='ip_blacklist')
    op.drop_index(op.f('ix_ip_blacklist_id'), table_name='ip_blacklist')
    op.drop_table('ip_blacklist')
    op.drop_index(op.f('ix_admin_login_history_id'), table_name='admin_login_history')
    op.drop_index(op.f('ix_admin_login_history_email'), table_name='admin_login_history')
    op.drop_table('admin_login_history')
    # ### end Alembic commands ###
