"""roles audit multitenant future tables

Revision ID: 9f8eb30a83d5
Revises: cf300765eb2d
Create Date: 2026-05-20 16:56:21.645237

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9f8eb30a83d5'
down_revision = 'cf300765eb2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=120), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_logs_app_id'), 'api_logs', ['app_id'], unique=False)
    op.create_index(op.f('ix_api_logs_company_id'), 'api_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_api_logs_id'), 'api_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_logs_request_id'), 'api_logs', ['request_id'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=120), nullable=False),
    sa.Column('transaction_reference', sa.String(length=80), nullable=True),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('commission_value', sa.Float(), nullable=False),
    sa.Column('amount_collected', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_app_id'), 'commissions', ['app_id'], unique=False)
    op.create_index(op.f('ix_commissions_company_id'), 'commissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_commissions_id'), 'commissions', ['id'], unique=False)
    op.create_index(op.f('ix_commissions_transaction_reference'), 'commissions', ['transaction_reference'], unique=False)
    op.create_table('failed_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_requests_app_id'), 'failed_requests', ['app_id'], unique=False)
    op.create_index(op.f('ix_failed_requests_company_id'), 'failed_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_failed_requests_id'), 'failed_requests', ['id'], unique=False)
    op.create_index(op.f('ix_failed_requests_request_id'), 'failed_requests', ['request_id'], unique=False)
    op.create_table('merchant_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=120), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=False),
    sa.Column('pending_balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_balances_app_id'), 'merchant_balances', ['app_id'], unique=False)
    op.create_index(op.f('ix_merchant_balances_company_id'), 'merchant_balances', ['company_id'], unique=False)
    op.create_index(op.f('ix_merchant_balances_id'), 'merchant_balances', ['id'], unique=False)
    op.create_table('merchant_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=120), nullable=False),
    sa.Column('wallet_reference', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_wallets_app_id'), 'merchant_wallets', ['app_id'], unique=False)
    op.create_index(op.f('ix_merchant_wallets_company_id'), 'merchant_wallets', ['company_id'], unique=False)
    op.create_index(op.f('ix_merchant_wallets_id'), 'merchant_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_merchant_wallets_wallet_reference'), 'merchant_wallets', ['wallet_reference'], unique=True)
    op.create_table('security_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=120), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_logs_app_id'), 'security_logs', ['app_id'], unique=False)
    op.create_index(op.f('ix_security_logs_company_id'), 'security_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_logs_id'), 'security_logs', ['id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=120), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_app_id'), 'settlements', ['app_id'], unique=False)
    op.create_index(op.f('ix_settlements_company_id'), 'settlements', ['company_id'], unique=False)
    op.create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    op.create_index(op.f('ix_settlements_reference'), 'settlements', ['reference'], unique=True)
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=120), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_app_id'), 'webhook_logs', ['app_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_company_id'), 'webhook_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_reference'), 'webhook_logs', ['reference'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=120), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_app_id'), 'withdrawals', ['app_id'], unique=False)
    op.create_index(op.f('ix_withdrawals_company_id'), 'withdrawals', ['company_id'], unique=False)
    op.create_index(op.f('ix_withdrawals_id'), 'withdrawals', ['id'], unique=False)
    op.create_index(op.f('ix_withdrawals_reference'), 'withdrawals', ['reference'], unique=True)
    op.add_column('connected_apps', sa.Column('company_id', sa.String(length=120), nullable=False))
    op.create_index(op.f('ix_connected_apps_company_id'), 'connected_apps', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connected_apps_company_id'), table_name='connected_apps')
    op.drop_column('connected_apps', 'company_id')
    op.drop_index(op.f('ix_withdrawals_reference'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_company_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_app_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_webhook_logs_reference'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_company_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_app_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_settlements_reference'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_company_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_app_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_security_logs_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_company_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_app_id'), table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index(op.f('ix_merchant_wallets_wallet_reference'), table_name='merchant_wallets')
    op.drop_index(op.f('ix_merchant_wallets_id'), table_name='merchant_wallets')
    op.drop_index(op.f('ix_merchant_wallets_company_id'), table_name='merchant_wallets')
    op.drop_index(op.f('ix_merchant_wallets_app_id'), table_name='merchant_wallets')
    op.drop_table('merchant_wallets')
    op.drop_index(op.f('ix_merchant_balances_id'), table_name='merchant_balances')
    op.drop_index(op.f('ix_merchant_balances_company_id'), table_name='merchant_balances')
    op.drop_index(op.f('ix_merchant_balances_app_id'), table_name='merchant_balances')
    op.drop_table('merchant_balances')
    op.drop_index(op.f('ix_failed_requests_request_id'), table_name='failed_requests')
    op.drop_index(op.f('ix_failed_requests_id'), table_name='failed_requests')
    op.drop_index(op.f('ix_failed_requests_company_id'), table_name='failed_requests')
    op.drop_index(op.f('ix_failed_requests_app_id'), table_name='failed_requests')
    op.drop_table('failed_requests')
    op.drop_index(op.f('ix_commissions_transaction_reference'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_company_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_app_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_api_logs_request_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_company_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_app_id'), table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
